### ISSUE TITLE
What should be in kameleoon-configuration.js?

### ISSUE THREAD

**Issue by ungarson** [pixelschrubber/grunting-kameleoon#1]
Is "username" an email which devteam use to login to the backoffice?
And what is token and what is timestamp?

**Comment by pixelschrubber** [comment]
@ungarson - yes, username is corresponding to the email address to log in to the backoffice. The token will be generated once authenticated. timestamp is automatically inserted. See https://support.kameleoon.com/hc/en-us/articles/208443429-REST-API-Server-Side-API-
