### ISSUE TITLE
What should be in url and status in configuration.json?

### ISSUE THREAD

**Issue by ungarson** [pixelschrubber/grunting-kameleoon#2]
In this configuration.json for example:
https://github.com/pixelschrubber/grunting-kameleoon/blob/master/tests/ab-sample/configuration.json

What should be in the url and in the status fields?

**Comment by ungarson** [comment]
Can i put there information about already existing test?

**Comment by pixelschrubber** [comment]
Put in the URL the page you would like to do a test for. Status will be updated automatically according to the test in the tool.

The script is not made to fetch information about already existing tests - one way street up to now. Feel free to do a pull request of you implementation about pulling the information from the backoffice.
