### ISSUE TITLE
How can i edit already existing test?

### ISSUE THREAD

**Issue by ungarson** [pixelschrubber/grunting-kameleoon#3]
Can i get a code of a project from the backoffice, edit it and then push it to the backoffice using this API? If yes, how can i do it?

**Comment by pixelschrubber** [comment]
Unfortunately this is not possible yet. Feel free to do a pull request of your feature doing so ;-)

**Comment by ungarson** [comment]
@pixelschrubber i can create

**Comment by ungarson** [comment]
If i had created a test in the backoffice, edited it locally and then i pushed it to the backoffice, will it work in this case? I don't have to pull the code in this case.
